
stages:
  - build
  - test
  - e2e
  - lint
  - deploy

cache:
  - paths:
      - node_modules/

before_script:
  - npm install
  - npm run lint:fix

# build stage
build:
  stage: build
  image: node:latest
  script:
    - npm run build

# test stage
test:
  stage: test
  image: node:latest
  script:
    - npm run test

e2e:
  stage: e2e
  image: cypress/included
  script:
  - npm run cy:run-e2e

# run eslint
lint:
  stage: lint
  image: node:latest
  script:
    - npm run lint:txt
  artifacts:
    paths:
      - eslint-report.txt # Generate eslint-report.txt artifact for ESLint output

# deploy stage
deploy:
  stage: deploy
  script:
    - npm install -g netlify-cli
    - netlify --version
    - npm run build
    - npx netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod --dir build/
  artifacts:
    paths:
      - build
  only:
    - main

