stages:
  - build
  - test
  - lint

cache:
  - paths:
      - node_modules/

before_script:
  - npm install
  - npm ci

# build stage
build:
  stage: build
  image: node:latest
  script:
    - npm run build

# test stage
test:
  stage: test
  image: node:latest
  script:
    - npm run test

# run eslint
lint:
  stage: lint
  image: node:latest
  script:
    - npm run lint