
stages:
  - build
  - test
  - lint
  - deploy

cache:
  - paths:
      - node_modules/

before_script:
  - npm install
  - npm ci

# build stage
build:
  stage: build
  image: node:latest
  script:
    - npm run build

# test stage
test:
  stage: test
  image: node:latest
  script:
    - npm run test

# run eslint
lint:
  stage: lint
  image: node:latest
  script:
    - npm run lint

# deploy stage: will be completed later
deploy:
  stage: deploy
  image: node:latest
  script:
    - npm run build && scp -i $AWS_KEY_PAIR -r build/* ec2-user@<EC34.224.64.68:http/reviewoger
  environment:
    name: prod
  only:
    - main
    - 55-create-ci-pipline
